### ISSUE TITLE
PubSubClient issue

### ISSUE THREAD

**Issue by darrylb123** [keerekeerweere/ESP32_SMA-Inverter-MQTT#8]
TBPubSubClient has been renamed which causes a build failure.
Refer to Issue in my repo.

**Comment by kommando828** [comment]
I also posted this issue on the library github and got this suggestion which also worked.

The fix is probably to simply use https://github.com/thingsboard/pubsubclient#v2.9.1 in the platformio.ini instead of the https://github.com/MathewHDYT/pubsubclient library. This would remove the need to adjust the #include to PubSubClient insead of TBPubSubClient  

but renaming allows the use of 2.9.3 and hopefully subsequent versions.

**Comment by keerekeerweere** [comment]
Thanks for your comment, have not been actively follwing up on the tool. the esp32's behave quite well lately. will update them and try out on one inverter.
greetings

**Comment by keerekeerweere** [comment]
pull request merged

**Comment by darrylb123** [comment]
Yes, I've got 3 in service, no problems with any. One is a very early
version, still rock solid.
